"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { CalendarDays, Users, ClipboardList, Bus, RefreshCw, Plus, ArrowRight, CircleAlert, CheckCircle2, Clock3 } from "lucide-react";
import { useGetOverviewQuery } from "@/services/api/operations.api";
import { useHeader } from "@/providers/header-provider";
import { PageHeader } from "@/components/shared/page-header";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { AddEmployeeDialog } from "@/components/employees/add-employee-dialog";
import { AddCustomerDialog } from "@/components/customers/add-customer-dialog";
import { AddFleetDialog } from "@/components/fleet/add-fleet-dialog";
import { DispatchStatusBadge } from "@/components/bookings/DispatchStatusBadge";
import { dateParts, formatTripDate } from "@/lib/workflow-api";

export default function OperationsDashboard() {
  const { setHeaderConfig } = useHeader();
  const [date, setDate] = useState(() => dateParts(new Date().toISOString(), "Australia/Sydney").date);
  const { currentData: data, isLoading, isFetching, isError, refetch } = useGetOverviewQuery(date, { pollingInterval: 30000, skipPollingIfUnfocused: true, refetchOnFocus: true, refetchOnReconnect: true, refetchOnMountOrArgChange: true });
  useEffect(() => { setHeaderConfig({ title: "Operations Dashboard" }); }, [setHeaderConfig]);
  const zone = data?.timeZone || "Australia/Sydney", dispatchLink = `/dashboard/dispatch?date=${date}`;
  const cards = data ? [
    { title: "Confirmed trip legs", value: data.metrics.confirmedTripLegs, hint: "Overlapping the selected day", Icon: CalendarDays, href: dispatchLink },
    { title: "Jobs needing allocation", value: data.metrics.jobsNeedingAllocation, hint: "Including partial allocations", Icon: ClipboardList, href: dispatchLink },
    { title: "Active employees", value: data.metrics.activeEmployees, hint: "Current active profiles", Icon: Users, href: "/dashboard/employees" },
    { title: "Active customers", value: data.metrics.activeCustomers, hint: "Current active accounts", Icon: Users, href: "/dashboard/customers" },
  ] : [];
  return <main className="mx-auto max-w-[1600px] space-y-6 p-6 lg:p-8">
    <PageHeader title="Operations Dashboard" description="Your daily schedule and the work that needs attention." breadcrumbs={[{ label: "Dashboard" }]} className="px-0 py-0 border-none" actions={<Button asChild className="gap-2 bg-blue-600 hover:bg-blue-700"><Link href="/dashboard/bookings/new"><Plus size={16} />New booking</Link></Button>} />
    <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-200 bg-white p-4"><div className="flex flex-wrap items-center gap-3"><CalendarDays size={18} className="text-blue-600" /><label className="text-sm font-medium" htmlFor="operating-date">Operating date</label><Input id="operating-date" type="date" className="w-auto" value={date} onChange={e => { if (/^\d{4}-\d{2}-\d{2}$/.test(e.target.value)) setDate(e.target.value); }} /><span className="text-xs text-slate-500">{zone}</span></div><div className="flex items-center gap-3"><span className="text-xs text-slate-500">{data ? `Updated ${new Intl.DateTimeFormat("en-AU", { timeStyle: "short", timeZone: zone }).format(new Date(data.generatedAt))}` : "Waiting for data"}</span><Button aria-label="Refresh dashboard" variant="outline" disabled={isFetching} onClick={() => refetch()}><RefreshCw size={15} className={isFetching ? "animate-spin" : ""} />Refresh</Button></div></div>
    {isError && <div role="alert" className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">{data ? "Refresh failed. Showing the last successful update." : "The dashboard could not be loaded. No values are being shown."} <Button variant="outline" onClick={() => refetch()}>Retry</Button></div>}
    {!data && (isLoading || isFetching) && <div role="status" className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[1, 2, 3, 4].map(i => <div key={i} className="h-32 animate-pulse rounded-2xl border bg-slate-100" />)}<p className="sr-only">Loading operations</p></div>}
    {data && <><section aria-label="Operations totals" className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(({ title, value, hint, Icon, href }) => <Link key={title} href={href} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition-colors hover:border-blue-300"><div className="flex items-center justify-between"><span className="text-sm font-medium text-slate-600">{title}</span><span className="rounded-lg bg-blue-50 p-2 text-blue-600"><Icon size={18} /></span></div><p className="mt-3 text-3xl font-semibold tracking-tight">{value}</p><p className="mt-2 text-xs text-slate-500">{hint}</p></Link>)}</section>
    <div className="grid items-start gap-6 xl:grid-cols-[minmax(0,1fr)_360px]"><section className="min-w-0 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 p-5"><div><h2 className="flex items-center gap-2 font-semibold"><Clock3 size={18} className="text-blue-600" />Day’s schedule</h2><p className="mt-1 text-xs text-slate-500">{date} · Includes overnight journeys</p></div><Button variant="outline" asChild><Link href={dispatchLink}>Open dispatch<ArrowRight size={15} /></Link></Button></div>{!data.schedule.length ? <div className="p-12 text-center text-sm text-slate-500"><CalendarDays size={28} className="mx-auto mb-3 text-slate-300" />No confirmed trips for this day.</div> : <div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="p-4">Time</th><th className="p-4">Customer & route</th><th className="p-4">Resources</th><th className="p-4">Status</th></tr></thead><tbody>{data.schedule.map(job => <tr key={job.id} className="border-t border-slate-100 hover:bg-slate-50/50"><td className="p-4 align-top text-xs text-slate-600"><p>{formatTripDate(job.start, zone)}</p><p className="mt-1 text-slate-400">to {formatTripDate(job.end, zone)}</p></td><td className="max-w-xs p-4 align-top"><Link className="font-semibold text-blue-700 hover:underline" href={`/dashboard/bookings/${job.bookingId}`}>{job.customer}</Link><p className="mt-1 text-xs text-slate-500">Job #{job.id} · {job.pickup} → {job.destination}</p></td><td className="p-4 align-top text-xs"><p className="mb-2 text-slate-500">{job.assigned}/{job.required} allocated</p>{job.assignments.map(a => <p key={a.id} className="mb-1">{a.driver} · {a.vehicle}</p>)}</td><td className="p-4 align-top"><DispatchStatusBadge status={job.status} /></td></tr>)}</tbody></table></div>}</section>
    <div className="space-y-6"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="flex items-center gap-2 font-semibold"><CircleAlert size={18} className="text-amber-600" />Needs attention<span className="ml-auto rounded-full bg-amber-50 px-2 py-1 text-xs text-amber-700">{data.attention.length}</span></h2><p className="mt-2 text-xs leading-relaxed text-slate-500">Allocations for the selected day; quotation and licence alerts as of today.</p><div className="mt-4 max-h-[480px] space-y-3 overflow-y-auto">{!data.attention.length && <p className="flex items-center gap-2 py-4 text-sm text-emerald-700"><CheckCircle2 size={17} />Nothing needs attention.</p>}{data.attention.map(item => <Link key={item.key} href={item.href} className={`block rounded-xl border p-3 hover:border-slate-400 ${item.tone === "rose" ? "border-rose-100 bg-rose-50/50" : "border-amber-100 bg-amber-50/50"}`}><p className="text-sm font-medium text-slate-800">{item.title}</p><p className="mt-1 break-words text-xs text-slate-500">{item.detail}</p></Link>)}</div></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="flex items-center gap-2 font-semibold"><Bus size={18} className="text-blue-600" />Fleet snapshot</h2><dl className="mt-4 space-y-3 text-sm">{[["Eligible active vehicles", data.fleet.eligibleActive], ["Scheduled for this day", data.fleet.scheduled], ["Maintenance", data.fleet.maintenance], ["Inactive", data.fleet.inactive]].map(([label, count]) => <div key={label} className="flex justify-between gap-3"><dt className="text-slate-500">{label}</dt><dd className="font-semibold">{count}</dd></div>)}</dl><p className="mt-4 text-xs leading-relaxed text-slate-500">Scheduled vehicles may also be eligible. Check dispatch for availability at a specific time.</p><Link href="/dashboard/fleet-ops" className="mt-4 inline-flex items-center gap-2 text-sm font-medium text-blue-700">Manage fleet<ArrowRight size={14} /></Link></section></div></div></>}
    <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="mb-4 font-semibold">Quick actions</h2><div className="flex flex-wrap gap-3"><AddEmployeeDialog /><AddCustomerDialog /><AddFleetDialog /><Button variant="outline" asChild><Link href={dispatchLink}><CalendarDays size={16} />Open dispatch</Link></Button></div></section>
  </main>;
}
