import { CalendarDays, Users, Bus, UserRound, MapPin, ReceiptText, Clock3, FileCheck2, Send, ClipboardList, CircleCheck, CircleAlert, type LucideIcon } from "lucide-react";
import type { ReactNode } from "react";
import { formatMoney } from "@/lib/workflow-api";
import { DispatchStatusBadge } from "./DispatchStatusBadge";

export const bookingStepIcons = [ClipboardList, MapPin, ReceiptText, Send, FileCheck2];
export function BookingSectionTitle({ title, description, icon: Icon = ClipboardList }: { title: string; description?: string; icon?: LucideIcon }) {
  return <div className="flex items-start gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-blue-50 text-blue-600"><Icon size={20} aria-hidden="true" /></span><div><h2 className="text-lg font-semibold tracking-tight text-slate-900">{title}</h2>{description && <p className="mt-1 text-sm leading-relaxed text-slate-500">{description}</p>}</div></div>;
}
export function WorkflowStatus({ label, value }: { label: string; value: string }) {
  const tone = /^(ACCEPTED|CONFIRMED|DELIVERED|COMPLETED|ASSIGNED)$/.test(value) ? "border-emerald-100 bg-emerald-50 text-emerald-800" : /^(DECLINED|FAILED|BOUNCED|BLOCKED|CANCELLED)$/.test(value) ? "border-rose-100 bg-rose-50 text-rose-800" : /^(SENT|QUEUED|AWAITING_RESPONSE|PENDING|UNASSIGNED|EXPIRED)$/.test(value) ? "border-amber-100 bg-amber-50 text-amber-800" : "border-slate-200 bg-slate-50 text-slate-700";
  const Icon = tone.includes("emerald") ? CircleCheck : tone.includes("rose") ? CircleAlert : Clock3;
  return <div className={`rounded-xl border p-4 ${tone}`}><p className="mb-2 text-xs font-medium opacity-80">{label}</p><p className="flex items-center gap-2 text-sm font-semibold"><Icon size={15} aria-hidden="true" />{value.replaceAll("_", " ")}</p></div>;
}
export function BookingOverview({ trip, booking, total, currency, hasQuotation, dirty, children }: { trip: any; booking: any; total: number; currency: string; hasQuotation: boolean; dirty: boolean; children?: ReactNode }) {
  const row = (Icon: LucideIcon, label: string, value: ReactNode) => <div className="flex gap-3"><Icon size={16} className="mt-0.5 shrink-0 text-slate-400" aria-hidden="true" /><div className="min-w-0"><dt className="text-xs text-slate-500">{label}</dt><dd className="mt-1 break-words text-sm font-medium text-slate-800">{value}</dd></div></div>;
  return <aside className="h-fit overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm lg:sticky lg:top-6"><div className="border-b border-slate-100 bg-slate-50/70 p-5"><p className="mb-2 text-[11px] font-semibold uppercase tracking-widest text-blue-600">Booking overview</p><h2 className="break-words text-lg font-semibold text-slate-900">{trip.subject || "Your next journey"}</h2><p className="mt-2 text-xs text-slate-500">{dirty ? "Unsaved changes" : booking ? `Booking #${booking.id}` : "New booking draft"}</p></div><div className="space-y-5 p-5"><dl className="space-y-4">{row(UserRound, "Customer", trip.customerName || trip.customerEmail || "Not selected")}{row(CalendarDays, "Departure", trip.date ? `${trip.date} · ${trip.startTime}` : "Not added")}{row(Clock3, "Arrival", trip.date ? `${trip.endDate || trip.date} · ${trip.endTime}` : "Not added")}</dl><p className="text-[11px] text-slate-500">{trip.timeZone}</p><div className="space-y-4 rounded-xl border border-slate-100 bg-slate-50/60 p-4"><div className="flex gap-3"><span className="mt-1 h-2.5 w-2.5 shrink-0 rounded-full border-2 border-blue-500" /><div className="min-w-0"><p className="text-[11px] text-slate-500">Pickup</p><p className="mt-1 break-words text-sm font-medium">{trip.pickup.address || "Not added"}</p></div></div>{trip.stops?.length > 0 && <p className="ml-5 text-xs text-slate-500">{trip.stops.length} intermediate stop{trip.stops.length === 1 ? "" : "s"}</p>}<div className="flex gap-3"><MapPin size={14} className="mt-1 shrink-0 text-blue-600" /><div className="min-w-0"><p className="text-[11px] text-slate-500">Destination</p><p className="mt-1 break-words text-sm font-medium">{trip.dropoff.address || "Not added"}</p></div></div></div><div className="grid grid-cols-2 gap-2 text-sm"><span className="flex items-center gap-2 rounded-lg bg-slate-50 p-2"><Users size={15} className="text-slate-400" />{trip.passengerCount} guests</span><span className="flex items-center gap-2 rounded-lg bg-slate-50 p-2"><Bus size={15} className="text-slate-400" />{trip.noOfVehicles} vehicles</span></div>{children}{booking && <div className="border-t border-slate-100 pt-4"><DispatchStatusBadge status={booking.dispatchStatus} /></div>}<div className="rounded-xl border border-blue-100 bg-blue-50/70 p-4"><p className="text-xs font-medium text-blue-700">{hasQuotation ? "Quotation total" : "Draft estimate"}</p><p className="mt-1 text-2xl font-semibold tracking-tight text-blue-950">{hasQuotation || total ? formatMoney(total, currency) : "Not priced yet"}</p><p className="mt-2 text-[11px] leading-relaxed text-blue-700">{dirty ? "Save changes before sharing with the customer." : "Dispatch opens after customer acceptance."}</p></div></div></aside>;
}
