import { ReceiptText, CalendarDays, Route } from "lucide-react";
import { formatMoney, formatTripDate } from "@/lib/workflow-api";
export function QuotationPreview({ quotation: q }: { quotation: any }) {
  const s = q.snapshot;
  return <article className="overflow-hidden rounded-2xl border border-slate-200 border-t-4 border-t-blue-500 bg-white p-6 sm:p-8 space-y-7 text-slate-800 shadow-sm">
    <header className="flex flex-wrap justify-between gap-4 border-b pb-6"><div><p className="text-sm font-semibold text-slate-500">{s.companyName}</p><h2 className="mt-2 flex items-center gap-3 text-2xl font-semibold tracking-tight"><ReceiptText size={24} className="text-blue-500" />Trip quotation</h2><p className="text-sm text-slate-500 mt-2">Q-{q.id} · Revision {q.revision}</p></div><div className="text-sm"><p className="font-semibold">Prepared for {s.customerName}</p><p>{s.customerEmail}</p><p className="mt-3 flex items-center gap-2"><CalendarDays size={15} className="text-blue-500" />Valid until {formatTripDate(q.expiresAt, s.timeZone)}</p><p className="text-slate-500">All trip times: {s.timeZone}</p></div></header>
    <div className="rounded-xl border border-slate-100 bg-slate-50/70 p-5"><p className="mb-2 flex items-center gap-2 text-xs font-semibold uppercase tracking-wide text-blue-600"><Route size={14} />Journey details</p><h3 className="text-lg font-semibold">{s.subject}</h3><p className="mt-3">{s.startLocation} → {s.endLocation}</p>{s.stops?.map((stop: any, i: number) => <p key={i} className="text-sm text-slate-500">Stop {i + 1}: {stop.address}</p>)}<p className="mt-3">{formatTripDate(s.startDateTime, s.timeZone)} — {formatTripDate(s.endDateTime, s.timeZone)}</p>{s.returnDateTime && <p>Return departure: {formatTripDate(s.returnDateTime, s.timeZone)}</p>}{s.recurrenceRule && <p className="mt-2">Repeats {s.recurrenceRule.type}, {s.recurrenceRule.startDate} to {s.recurrenceRule.endDate}{s.recurrenceRule.days?.length ? ` (${s.recurrenceRule.days.map((d: number) => ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"][d]).join(", ")})` : ""}</p>}<p className="mt-2 text-sm text-slate-500">{s.passengerCount} passengers · {s.noOfVehicles} vehicles · {s.tripCount} trip legs</p></div>
    <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-slate-200 bg-slate-50 text-left text-slate-500"><th className="py-3">Description</th><th>Qty</th><th className="text-right">Unit price</th><th className="text-right">Amount</th></tr></thead><tbody>{q.items.map((item: any, i: number) => <tr key={i} className="border-b"><td className="py-4 pr-4 whitespace-pre-wrap">{item.description}</td><td>{item.quantity}</td><td className="text-right whitespace-nowrap">{formatMoney(item.unitPriceMinor, q.currency)}</td><td className="text-right whitespace-nowrap">{formatMoney(item.totalMinor, q.currency)}</td></tr>)}</tbody></table></div>
    <dl className="ml-auto max-w-xs space-y-2"><div className="flex justify-between"><dt>Subtotal</dt><dd>{formatMoney(q.subtotalMinor, q.currency)}</dd></div><div className="flex justify-between"><dt>Discount</dt><dd>−{formatMoney(q.discountMinor, q.currency)}</dd></div><div className="flex justify-between"><dt>Tax ({q.taxBasisPoints / 100}%)</dt><dd>{formatMoney(q.taxMinor, q.currency)}</dd></div><div className="flex justify-between rounded-lg bg-blue-50 p-3 text-lg font-semibold text-blue-950"><dt>Total {q.currency}</dt><dd>{formatMoney(q.totalMinor, q.currency)}</dd></div></dl>
    {q.message && <p className="whitespace-pre-wrap">{q.message}</p>}<section className="border-t pt-6"><h3 className="font-semibold mb-2">Terms & conditions</h3><p className="text-sm text-slate-600 whitespace-pre-wrap">{q.terms || "No additional terms."}</p></section>
  </article>;
}
