// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Using the env() helper solves the "undefined" TypeScript error
    url: env("DATABASE_URL"),
    // DIRECT_URL is used for Migrations and 'db push' to bypass the pooler
    directUrl: env("DIRECT_URL"),
  },
});
