name: Frontend CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

defaults:
  run:
    working-directory: frontendServer # Ensure this matches your folder name

jobs:
  test-and-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: frontendServer/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Run Linting
        run: npm run lint

      - name: Run Tests
        run: npm test # Ensure this command is set in your package.json
